//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public string CaseId { get; set; }
        public string CaseName { get; set; }
        public string Plaintiff { get; set; }
        public string Defender { get; set; }
        public string OpponentLawyer { get; set; }
        public string CaseDiscription { get; set; }
        public System.DateTime startDate { get; set; }
        public System.Guid CourtId { get; set; }
        public string CaseType { get; set; }
        public string ClientId { get; set; }
        public Nullable<bool> isComplete { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Court Court { get; set; }
    }
}
