//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseHearingDate
    {
        public int CaseHearingId { get; set; }
        public string CaseId { get; set; }
        public System.DateTime HearingDate { get; set; }
        public Nullable<System.TimeSpan> HearingTime { get; set; }
    }
}
