//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public string userName { get; set; }
        public string password { get; set; }
        public int userId { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string Contact { get; set; }
        public string RoleID { get; set; }
    
        public virtual UserRole UserRole { get; set; }
    }
}
